### ISSUE TITLE
zh_CN.lproj复制到soure目录重启后，app界面仍是英文

### ISSUE THREAD

**Issue by PM100Fun** [aoaoho/DEVONthink-Chinese#1]
RT，pro office，2.9.17，非正版

**Comment by aoaoho** [comment]
soure目录？请仔细看README，确保是`DEVONthink Pro Office.app/Contents/Resources/`目录下，我这里v2.9.17以及刚刚升级的新版本v2.10都是有效的。

语言包理论上跟是否正版无关。

**Comment by PM100Fun** [comment]
dalao好，就是Resources/下的目录，跟en.lproj同级的

**Comment by PM100Fun** [comment]
难道语言跟随了系统？？

**Comment by aoaoho** [comment]
呃，是，软件默认语言是根据当前系统语言列表来读取的。
但有办法指定某个软件的默认语言，你自己google一下`mac 系统语言 软件语言`

**Comment by PM100Fun** [comment]
下载了个Language Switcher搞定了

**Comment by PM100Fun** [comment]
dalao，能不能把偏好设置里面的也翻译一下？

**Comment by aoaoho** [comment]
暂时做不到 😕 
> 包括偏好设置在内的部分界面仍然存在英文，可能是这部分内容未放到资源文件内

**Comment by aoaoho** [comment]
@RivieraS 偏好设置界面搞定了

**Comment by PM100Fun** [comment]
牛逼啊大佬
