### ISSUE TITLE
3.0版本

### ISSUE THREAD

**Issue by Guwl** [aoaoho/DEVONthink-Chinese#2]
请问有计划编写3.0版本的语言包吗？

**Comment by aoaoho** [comment]
正式版发布之前应该不会考虑做。

**Comment by RiverChow** [comment]
希望正式版发布之后能编写3.0版本的语言包！感谢~

**Comment by jimyong88** [comment]
请问有3.0的更新计划吗？😊

**Comment by aoaoho** [comment]
我自己已经不再使用 DEVONthink 了，所以也没有翻译 3.0 的打算。

**Comment by JimmyLv** [comment]
想请教一下「不再使用 DEVONthink」的原因呢？

**Comment by aoaoho** [comment]
主要是我自己的工作流程有变化，DT本身还是很棒的。
